### ISSUE TITLE
HTML of Chapter 1

### ISSUE THREAD

**Issue by scribbly** [safenetwork/primer.safenetwork.org#2]
The '20 Fundamental Principles of the SAFE Network' I think needs some work to make it more correct (for a machine) and layout correctly (for the human) -- have no idea if I've done this correctly or not, but added an update.

As I said in the comment "I'm not a fan of all the Line Breaks, as these types of formatting are better handled in CSS, but have left as is, because the rest of the document is formatted like that.", but we all have our individual styles ;)

**Comment by JPL1** [comment]
Thanks. I'm making some updates to the primer at the moment to bring it up to date. I'll check out these layout suggestions for the next iteration once I'm done.

**Comment by scribbly** [comment]
> I'll check out these layout suggestions for the next iteration once I'm done.

As I said: I'd be happy to do the all the chapters if you'd like... but I'd be suggesting moving more of the layout to CSS and making the HTML nodes more machine readable (i.e. structure makes sense).
